### PR TITLE
Adding altimeter

### PR DESCRIPTION
**Pull request by mcongrove**
Switched the `dataref` from 24 to 20 to ensure we get the _indicated_ altitude.

Also, I'm using EaselJS to create the barometric pressure reading. This ensures accuracy when setting it. However, I'm not really sure exactly how to properly add the text to the canvas. If you look at Line 65 of the `altitude/client/altitude.js` file you'll see what I've done in the interim. Is there a better way?

### CODE REVIEW

**Comment by dmolin** [comment]
Cool stuff Matthew :)
Re: pressure : It certainly works this way, nothing to say about it. another way to do it, maintaining the nice animation you have in the real one, is to draw the number on a disc and put the disc as the first layered image. then it could be simply a matter of rotating the disc when the pressure changes. 
Like in the following horrible image:
numbered disc
But this is just an idea for a possible improvement, since the current implementation already does an excellent job :)

**Comment by mcongrove** [comment]
I thought about doing it that way, but when I used to fly I always hated how hard it was to see the notches and get the pressure just right. That would be especially true if someone resizes their browser down. A lot of the newer altimeters use windows with the numerical values like in the design I did to be more readable and precise:

altimeter

The problem with the way I did the pressure is it's not adding to the stack at the right z-level. I think it has to do with the `load()` (Line 98 in `widgets.js`) callback for the images. The image isn't added to the stage immediately, but the text is, so the text is behind the images. Ideally, the text should be above the `altitude_gear` but below the needles.

**Comment by dmolin** [comment]
To be honest I like the current implementation of the display for the
pressure. It's easier to read. so, for me no reasons to look for other
implementations tbh.
Anyway, I solved the problem with the proper sequencing of the canvas
layers. Now everything stacks correctly, so I moved the pressure indicator
at its correct place, before the needles. :)
When layering StageImages now you can use 'beforeRender' and 'afterRender'
callback hooks. the first is called "before" the image is added to the
stage, then the latter. "load" still works and is also called before the
image is added to the stage (as for "next", that is called after the
addition to the stage).

If this week I find the necessary time I'll probably start a big chunk of
work on it, so please hold your horses from other changes (other than
designing new widgets if you wish :))


send replies to:
Davide Alberto Molin
davide.molin@gmail.com

find me on:
LinkedIn: http://www.linkedin.com/in/davidemolin
My Homepage: http://www.davidemolin.com
My Online Courses: http://fedtraining.usefedora.com
My GitHub: http://github.com/dmolin
My Blog: http://developme.wordpress.com
My Tweets: http://www.twitter.com/davidemolin
My Vimeo: http://vimeo.com/davidemolin

On Mon, Jan 19, 2015 at 10:30 PM, Matthew Congrove <notifications@github.com

**Comment by mcongrove** [comment]
Awesome, thanks for fixing that. I've got a busy week at work but if I find some free time I'll start on some designs.

Here's my personal to-do list: https://github.com/mcongrove/flightSimPanels/wiki/To-Do-List

**Comment by dmolin** [comment]
Yeah me too. .. actually, this has been the first time in a while since the
last time I committed code on this project.  :)

**Pull request merged**
